const KEYS={language:"routeTranquille.language",info:"routeTranquille.personalInfo"};
const TERMS={fr:{fuel:"station service",rest:"aire de repos camping car",pharmacy:"pharmacie",hospital:"hôpital",garage:"garage automobile",police:"commissariat de police"},sr:{fuel:"benzinska pumpa",rest:"odmorište kamp za kampere",pharmacy:"apoteka",hospital:"bolnica",garage:"auto servis",police:"policijska stanica"}};
const state={language:localStorage.getItem(KEYS.language)||(navigator.language.toLowerCase().startsWith("sr")?"sr":"fr"),translations:{},info:readInfo()};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const el={dialog:$("#emergency-dialog"),list:$("#emergency-list"),country:$("#emergency-country"),form:$("#personal-info-form"),summary:$("#info-summary"),summaryContent:$("#summary-content"),toast:$("#toast"),dot:$("#network-dot"),network:$("#network-status")};
function readInfo(){try{return JSON.parse(localStorage.getItem(KEYS.info))||{}}catch{return{}}}
function value(object,path){return path.split(".").reduce((v,k)=>v?.[k],object)}
function t(key){return value(state.translations,key)||key}
async function setLanguage(language){try{const response=await fetch(`./i18n/${language}.json`);if(!response.ok)throw Error();state.translations=await response.json();state.language=language;localStorage.setItem(KEYS.language,language);translate()}catch{toast(language==="sr"?"Prevod nije dostupan.":"La traduction est indisponible.")}}
function translate(){document.documentElement.lang=state.language;document.title=`${t("app.name")} – ${t("app.tagline")}`;$$('[data-i18n]').forEach(x=>x.textContent=t(x.dataset.i18n));$$('[data-i18n-placeholder]').forEach(x=>x.placeholder=t(x.dataset.i18nPlaceholder));$$('[data-i18n-aria-label]').forEach(x=>x.setAttribute("aria-label",t(x.dataset.i18nAriaLabel)));$$('[data-language]').forEach(x=>{const active=x.dataset.language===state.language;x.classList.toggle("is-active",active);x.setAttribute("aria-pressed",active)});network();renderEmergency();renderSummary()}
function renderEmergency(){const data=state.translations.emergency;if(!data)return;el.country.textContent=data.country;el.list.replaceChildren();data.numbers.forEach(item=>{const a=document.createElement("a");a.className="emergency-call";a.href=`tel:${item.number}`;a.setAttribute("aria-label",`${item.label} ${item.number}`);const name=document.createElement("span"),phone=document.createElement("strong");name.textContent=item.label;phone.textContent=item.number;a.append(name,phone);el.list.append(a)})}
function openEmergency(){renderEmergency();el.dialog.showModal?el.dialog.showModal():el.dialog.setAttribute("open","")}
function closeEmergency(){el.dialog.close?el.dialog.close():el.dialog.removeAttribute("open")}
function openMap(service){const term=encodeURIComponent(TERMS[state.language][service]).replace(/%20/g,"+");const base=`https://www.google.com/maps/search/${term}`;const tab=window.open("","_blank");const go=url=>tab?tab.location.href=url:location.href=url;if(!navigator.geolocation)return go(base);toast(t("location.searching"));navigator.geolocation.getCurrentPosition(({coords})=>go(`${base}/@${coords.latitude.toFixed(6)},${coords.longitude.toFixed(6)},14z`),()=>{toast(t("location.fallback"));go(base)},{timeout:7000,maximumAge:300000})}
function showView(name){$$('.view').forEach(view=>{const active=view.dataset.view===name;view.hidden=!active;view.classList.toggle("is-active",active)});$$('.nav-button[data-go-to]').forEach(button=>{const active=button.dataset.goTo===name;button.classList.toggle("is-active",active);active?button.setAttribute("aria-current","page"):button.removeAttribute("aria-current")});scrollTo({top:0,behavior:"smooth"});$(`[data-view="${name}"] h1`)?.focus({preventScroll:true})}
function populate(){Object.entries(state.info).forEach(([name,val])=>{const field=el.form.elements.namedItem(name);if(field)field.value=val})}
function save(event){event.preventDefault();state.info=Object.fromEntries([...new FormData(el.form)].map(([k,v])=>[k,String(v).trim()]));localStorage.setItem(KEYS.info,JSON.stringify(state.info));renderSummary();toast(t("info.saved"))}
function renderSummary(){const fields=[["fullName",t("info.fullName")],["bloodType",t("info.bloodType")],["allergies",t("info.allergies")],["medications",t("info.medications")],["emergencyName",t("info.emergencyContact")],["emergencyPhone",t("common.phone")],["vehiclePlate",t("info.plate")]].filter(([key])=>state.info[key]);el.summaryContent.replaceChildren();el.summary.classList.toggle("is-empty",!fields.length);el.summary.querySelector(".secondary-button").textContent=t(fields.length?"summary.edit":"summary.add");if(!fields.length)return;const list=document.createElement("dl");list.className="summary-list";fields.forEach(([key,label])=>{const row=document.createElement("div"),dt=document.createElement("dt"),dd=document.createElement("dd");row.className="summary-item";dt.textContent=label;dd.textContent=state.info[key];row.append(dt,dd);list.append(row)});el.summaryContent.append(list)}
let timer;function toast(message){clearTimeout(timer);el.toast.textContent=message;el.toast.classList.add("is-visible");timer=setTimeout(()=>el.toast.classList.remove("is-visible"),3000)}
function network(){const online=navigator.onLine;el.dot.classList.toggle("is-offline",!online);el.network.textContent=t(online?"status.online":"status.offline")}
$$('[data-language]').forEach(x=>x.addEventListener("click",()=>setLanguage(x.dataset.language)));$$('[data-service]').forEach(x=>x.addEventListener("click",()=>openMap(x.dataset.service)));$$('[data-go-to]').forEach(x=>x.addEventListener("click",()=>showView(x.dataset.goTo)));$$('[data-open-emergency],#emergency-button').forEach(x=>x.addEventListener("click",openEmergency));$("#close-emergency").addEventListener("click",closeEmergency);$("#close-emergency-bottom").addEventListener("click",closeEmergency);el.dialog.addEventListener("click",e=>{if(e.target===el.dialog)closeEmergency()});el.form.addEventListener("submit",save);addEventListener("online",network);addEventListener("offline",network);populate();setLanguage(state.language);if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>toast(t("status.cacheError"))));
