const STORAGE_KEYS={language:"routeTranquille.language",lastPosition:"routeTranquille.lastKnownPosition"};
const SEARCH_TERMS={fr:{fuel:["station service","station service nearby"],garage:["garage","garage nearby"],pharmacy:["pharmacie","pharmacy nearby"],hospital:["hôpital","hospital nearby"]},sr:{fuel:["benzinska pumpa","gas station nearby"],garage:["auto servis","garage nearby"],pharmacy:["apoteka","pharmacy nearby"],hospital:["bolnica","hospital nearby"]}};
const state={language:localStorage.getItem(STORAGE_KEYS.language)||(navigator.language.toLowerCase().startsWith("sr")?"sr":"fr"),translations:{},position:loadLastKnownPosition(),positionSource:loadLastKnownPosition()?"stored":"none",locating:false,activeView:"home"};
const elements={toast:document.querySelector("#toast"),networkDot:document.querySelector("#network-dot"),networkText:document.querySelector("#network-text")};
function detectLanguage(){return navigator.language.toLowerCase().startsWith("sr")?"sr":"fr"}
function valueAt(object,path){return path.split(".").reduce((value,key)=>value?.[key],object)}
function t(path){return valueAt(state.translations,path)||path}
async function loadLanguage(language){try{const response=await fetch(`./i18n/${language}.json`);if(!response.ok)throw Error();state.translations=await response.json();state.language=language;localStorage.setItem(STORAGE_KEYS.language,language);applyTranslations()}catch{showToast(language==="sr"?"Prevod nije dostupan.":"La traduction est indisponible.")}}
function applyTranslations(){document.documentElement.lang=state.language;document.title=`Route Tranquille – ${t("home.subtitle")}`;document.querySelectorAll("[data-i18n]").forEach(element=>element.textContent=t(element.dataset.i18n));document.querySelectorAll("[data-i18n-aria-label]").forEach(element=>element.setAttribute("aria-label",t(element.dataset.i18nAriaLabel)));document.querySelectorAll("[data-language]").forEach(button=>{const active=button.dataset.language===state.language;button.classList.toggle("is-active",active);button.setAttribute("aria-pressed",String(active))});renderPositionPanels();renderNearbyActions();renderChecklists();updateNetworkStatus()}
// Centralised GPS helper with clear browser error mapping.
function getCurrentPosition(){if(!navigator.geolocation)return Promise.reject({messageKey:"location.unsupported"});return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,error=>reject({messageKey:({1:"location.denied",2:"location.unavailable",3:"location.timeout"})[error.code]||"location.error"}),{enableHighAccuracy:true,timeout:12000,maximumAge:60000}))}
async function refreshPosition(){if(state.locating)return;state.locating=true;renderPositionPanels();try{const result=await getCurrentPosition();state.position={latitude:result.coords.latitude,longitude:result.coords.longitude,accuracy:result.coords.accuracy,timestamp:result.timestamp||Date.now()};state.positionSource="current";saveLastKnownPosition(state.position);showToast(t("location.updated"))}catch(error){state.positionSource=state.position?"stored":"error";showToast(t(error.messageKey||"location.error"))}finally{state.locating=false;renderPositionPanels()}}
function saveLastKnownPosition(position){localStorage.setItem(STORAGE_KEYS.lastPosition,JSON.stringify(position))}
function loadLastKnownPosition(){try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEYS.lastPosition));return stored?.latitude!=null&&stored?.longitude!=null?stored:null}catch{return null}}
function buildGoogleMapsUrl(query,lat,lon){const locationQuery=lat!=null&&lon!=null?`${query} near ${lat},${lon}`:query;return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(locationQuery)}`}
function buildPositionUrl(lat,lon){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${lat},${lon}`)}`}
function buildOsmUrl(lat,lon){return `https://www.openstreetmap.org/?mlat=${encodeURIComponent(lat)}&mlon=${encodeURIComponent(lon)}#map=16/${encodeURIComponent(lat)}/${encodeURIComponent(lon)}`}
function positionText(prefixKey="share.positionPrefix"){return state.position?`${t(prefixKey)} ${buildPositionUrl(state.position.latitude,state.position.longitude)}`:null}
async function copyPosition(options={}){const text=positionText(options.prefixKey);if(!text){showToast(t("location.noPosition"));refreshPosition();return false}try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else{const area=document.createElement("textarea");area.value=text;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.append(area);area.select();const copied=document.execCommand("copy");area.remove();if(!copied)throw Error()}showToast(options.fallback?t("share.unavailableCopied"):t("share.copied"));return true}catch{window.prompt(t("share.manualCopy"),text);return false}}
async function sharePosition(){const text=positionText("share.helpPrefix");if(!text){showToast(t("location.noPosition"));refreshPosition();return}if(navigator.share)try{await navigator.share({title:"Route Tranquille",text});return}catch(error){if(error.name==="AbortError")return}await copyPosition({prefixKey:"share.helpPrefix",fallback:true})}
function callEmergency(){window.location.href="tel:112"}
function openNearby(type){const [localized,generic]=(SEARCH_TERMS[state.language]||SEARCH_TERMS.fr)[type];openExternalMap(buildGoogleMapsUrl(state.position?localized:generic,state.position?.latitude,state.position?.longitude))}
function openCurrentPosition(provider="google"){if(!state.position){showToast(t("location.noPosition"));refreshPosition();return}openExternalMap(provider==="osm"?buildOsmUrl(state.position.latitude,state.position.longitude):buildPositionUrl(state.position.latitude,state.position.longitude))}
function openExternalMap(url){if(!navigator.onLine){showToast(t("network.mapsOffline"));return}window.open(url,"_blank","noopener,noreferrer")}
function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function formatDate(timestamp){return new Intl.DateTimeFormat(state.language==="sr"?"sr-RS":"fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(timestamp))}
function renderPositionPanels(){document.querySelectorAll("[data-position-panel]").forEach(container=>{const compact=container.dataset.compact==="true",position=state.position,statusKey=state.locating?"location.locating":state.positionSource==="current"?"location.current":state.positionSource==="stored"?"location.lastKnown":state.positionSource==="error"?"location.noPosition":"location.ready";container.innerHTML=`<section class="position-card"><div class="position-heading"><div><p class="position-label">${escapeHtml(t("location.title"))}</p><p class="position-state ${state.positionSource==="error"?"is-error":""}">${escapeHtml(t(statusKey))}</p></div><button class="refresh-button" type="button" data-refresh-position ${state.locating?"disabled":""}>${escapeHtml(t("actions.refresh"))}</button></div><div class="coordinates"><div class="coordinate"><span>${escapeHtml(t("location.latitude"))}</span><strong>${position?position.latitude.toFixed(6):"—"}</strong></div><div class="coordinate"><span>${escapeHtml(t("location.longitude"))}</span><strong>${position?position.longitude.toFixed(6):"—"}</strong></div><div class="coordinate"><span>${escapeHtml(t("location.accuracy"))}</span><strong>${position?.accuracy!=null?`${Math.round(position.accuracy)} m`:"—"}</strong></div></div>${position?`<p class="position-meta">${escapeHtml(t("location.updatedAt"))} ${escapeHtml(formatDate(position.timestamp))}</p>`:""}${compact?"":`<div class="position-actions"><button class="primary-action" data-copy-position>${escapeHtml(t("actions.copy"))}</button><button class="primary-action" data-share-position>${escapeHtml(t("actions.share"))}</button><button class="map-action" data-open-position>${escapeHtml(t("actions.openMaps"))}</button><button class="secondary-action" data-open-osm>${escapeHtml(t("actions.openOsmShort"))}</button></div>`}${navigator.onLine?"":`<p class="offline-note">${escapeHtml(t("network.offlineNote"))}</p>`}</section>`})}
function renderNearbyActions(){document.querySelectorAll("[data-nearby-actions]").forEach(container=>container.innerHTML=["fuel","garage","pharmacy","hospital"].map(type=>`<button class="map-action" data-nearby="${type}">${escapeHtml(t(`actions.${type}`))}</button>`).join(""))}
function renderChecklists(){document.querySelectorAll("[data-checklist]").forEach(container=>{const items=valueAt(state.translations,`checklists.${container.dataset.checklist}.items`)||[];container.innerHTML=`<section class="checklist-card"><h2>${escapeHtml(t("checklists.title"))}</h2><ul class="checklist">${items.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}</ul></section>`})}
function showView(viewName){state.activeView=viewName;document.querySelectorAll(".view").forEach(view=>{const active=view.dataset.view===viewName;view.hidden=!active;view.classList.toggle("is-active",active)});document.querySelectorAll(".nav-button[data-go-to]").forEach(button=>{const active=button.dataset.goTo===viewName;button.classList.toggle("is-active",active);active?button.setAttribute("aria-current","page"):button.removeAttribute("aria-current")});window.scrollTo({top:0,behavior:"smooth"});document.querySelector(`[data-view="${viewName}"] h1`)?.focus({preventScroll:true});if(viewName!=="home")refreshPosition()}
function updateNetworkStatus(){const online=navigator.onLine;elements.networkDot.classList.toggle("is-offline",!online);elements.networkText.textContent=t(online?"network.online":"network.offline");renderPositionPanels()}
let toastTimer;function showToast(message){clearTimeout(toastTimer);elements.toast.textContent=message;elements.toast.classList.add("is-visible");toastTimer=setTimeout(()=>elements.toast.classList.remove("is-visible"),3400)}
document.addEventListener("click",event=>{const target=event.target;const goTo=target.closest("[data-go-to]"),language=target.closest("[data-language]"),refresh=target.closest("[data-refresh-position]"),copy=target.closest("[data-copy-position]"),share=target.closest("[data-share-position]"),nearby=target.closest("[data-nearby]"),openPosition=target.closest("[data-open-position]"),openOsm=target.closest("[data-open-osm]"),emergency=target.closest("[data-call-emergency]");if(goTo)showView(goTo.dataset.goTo);else if(language)loadLanguage(language.dataset.language);else if(refresh)refreshPosition();else if(copy)copyPosition();else if(share)sharePosition();else if(nearby)openNearby(nearby.dataset.nearby);else if(openPosition)openCurrentPosition("google");else if(openOsm)openCurrentPosition("osm");else if(emergency)callEmergency()});
window.addEventListener("online",updateNetworkStatus);window.addEventListener("offline",updateNetworkStatus);loadLanguage(state.language);if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>showToast(t("network.cacheError"))));
